debug: true
server:
  port: 443
  ssl:
    enabled: true
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: secmeapi
    key-store-password: secmeapi

auth0:
  audience: https://sec-me-api.com/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://paradocx.us.auth0.com/