# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - secme-api

on:
  push:
    branches:
      - docker-deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_03146891c8514519bf26da533aeab67e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_eb917933d36848eeaeb02fcdb29e99ce }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_03146891c8514519bf26da533aeab67e }}/secme-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'secme-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_484b632b063c4b2b94b9fff26c6fad71 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_03146891c8514519bf26da533aeab67e }}/secme-api:${{ github.sha }}'